on:
  issue_comment:
    types: [created, deleted]

name: Azure/CLI - the actual repo

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.Azure_cred_login_obj }}

    - name: Checkout                                                                    
      uses: actions/checkout@v1                                                           


    - name: Azure cli
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/cliScript.sh
          $GITHUB_WORKSPACE/cliScript.sh
